# SPDX-License-Identifier: 0BSD
# Author: Makkhawan Sardlah

name: CI

on: 
  push:
    paths:
      - .github/workflows/**
  workflow_dispatch:

permissions:
  contents: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'
      - uses: actions/checkout@v6
      - name: download file test
        run: |
          cd internal/tests
          mkdir test
          wget https://www.python.org -P test
      - name: Test
        run: |
          go run main.go
          rm -r out test
      # - uses: stefanzweifel/git-auto-commit-action@v6
      #   with:
      #     commit_message: "Auto-test"
